// script.js
import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js';
import { getAuth, signInWithCustomToken, signInAnonymously, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js';
import { getFirestore, doc, setDoc, getDoc, onSnapshot } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js';

// Get Firebase globals from the environment
const firebaseConfig = typeof __firebase_config !== 'undefined' ? JSON.parse(__firebase_config) : {};
const initialAuthToken = typeof __initial_auth_token !== 'undefined' ? __initial_auth_token : null;
const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';

// Initialize Firebase services
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

// Translations for key UI elements
const translations = {
  English: {
    home: 'Home',
    about: 'About',
    contact: 'Contact',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    signUp: 'Sign Up',
    welcome: 'Welcome to GreenSpark',
    tagline: 'Empowering the farmer – cultivating the future',
    addressingChallenges: 'Addressing Key Challenges',
    challengesText: 'Farmers face many challenges today, from climate change and resource management to market access and financial security. GreenSpark provides the tools and information needed to overcome these obstacles and thrive.',
    cropDetails: 'Crop Details',
    cropDetailsText: 'Get information on water, soil, and fertilizers.',
    weather: 'Weather',
    weatherText: 'Real-time weather updates and alerts.',
    pesticides: 'Pesticides',
    pesticideText: 'Find suitable pesticides and fertilizers for your crops.',
    investmentHouse: 'Investment House',
    investmentHouseText: 'Access loan and insurance details.',
    members: 'Members',
    registeredMembers: 'Total number of registered members on our platform, growing daily!',
    help: 'Help',
    settings: 'Settings',
    chatbot: 'Chatbot',
    aboutTitle: 'About GreenSpark',
    aboutText1: 'GreenSpark is a comprehensive digital platform designed to support and empower farmers. We believe that by providing accessible information and innovative tools, we can help agricultural communities thrive in a changing world.',
    aboutText2: 'Our mission is to bridge the gap between traditional farming practices and modern technology. We offer a one-stop solution for vital agricultural needs, from real-time weather alerts and crop management advice to financial support resources.',
    aboutText3: 'Our team is dedicated to building a sustainable future for agriculture, one farmer at a time.',
    contactTitle: 'Contact Us',
    contactText: 'Have a question or need support? Fill out the details below and we\'ll get back to you as soon as possible.',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourQuery: 'Your Query',
    submitQuery: 'Submit Query',
    reachUs: 'Alternatively, you can reach us directly:',
    profileTitle: 'Profile',
    profileLoading: 'Loading profile...',
    editProfile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    searchCrop: 'Search for a crop...',
    water: 'Water',
    soil: 'Soil',
    fertilizers: 'Fertilizers',
    pesticidesLabel: 'Pesticides',
    weatherTitle: 'Weather Forecast',
    weatherText2: 'Get up-to-date weather information for your location and receive alerts for severe weather conditions.',
    currentWeather: 'Current Weather:',
    alerts: 'Alerts:',
    floodAdvisory: 'FLOOD ADVISORY IN EFFECT',
    rainExpected: 'Heavy rainfall expected in the next 24 hours. Recommended action: Ensure proper drainage and secure low-lying crops.',
    pesticideTitle: 'Pesticides & Fertilizers',
    pesticideText2: 'Find information on the right pesticides and fertilizers for your crops and soil.',
    organicFertilizers: 'Organic Fertilizers',
    syntheticPesticides: 'Synthetic Pesticides',
    investmentTitle: 'Investment House',
    investmentText2: 'Resources to help you secure your financial future, including low-interest loans and crop insurance.',
    lowInterestLoans: 'Low-Interest Loans',
    cropInsurance: 'Crop Insurance',
    theme: 'Theme',
    language: 'Language',
    upgradeAccount: 'Upgrade Your Account',
    upgradeText: 'Unlock premium features like advanced analytics, personalized recommendations, and expert support.',
    learnMore: 'Learn More & Upgrade',
  },
  Hindi: {
    home: 'होम',
    about: 'हमारे बारे में',
    contact: 'संपर्क करें',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    login: 'लॉग इन',
    signUp: 'साइन अप',
    welcome: 'ग्रीनस्पार्क में आपका स्वागत है',
    tagline: 'किसान को सशक्त बनाना – भविष्य की खेती',
    addressingChallenges: 'मुख्य चुनौतियों का समाधान',
    challengesText: 'किसान आज जलवायु परिवर्तन, संसाधन प्रबंधन, बाजार पहुंच और वित्तीय सुरक्षा जैसी कई चुनौतियों का सामना करते हैं। ग्रीनस्पार्क इन बाधाओं को दूर करने और फलने-फूलने के लिए आवश्यक उपकरण और जानकारी प्रदान करता है।',
    cropDetails: 'फसल की जानकारी',
    cropDetailsText: 'पानी, मिट्टी और उर्वरकों के बारे में जानकारी प्राप्त करें।',
    weather: 'मौसम',
    weatherText: 'वास्तविक समय मौसम अपडेट और अलर्ट।',
    pesticides: 'कीटनाशक',
    pesticideText: 'अपनी फसलों के लिए उपयुक्त कीटनाशकों और उर्वरकों का पता लगाएं।',
    investmentHouse: 'निवेश गृह',
    investmentHouseText: 'ऋण और बीमा विवरण तक पहुंचें।',
    members: 'सदस्य',
    registeredMembers: 'हमारे प्लेटफ़ॉर्म पर पंजीकृत सदस्यों की कुल संख्या, जो प्रतिदिन बढ़ रही है!',
    help: 'सहायता',
    settings: 'सेटिंग्स',
    chatbot: 'चैटबॉट',
    aboutTitle: 'ग्रीनस्पार्क के बारे में',
    aboutText1: 'ग्रीनस्पार्क एक व्यापक डिजिटल प्लेटफ़ॉर्म है जिसे किसानों का समर्थन और सशक्तिकरण करने के लिए डिज़ाइन किया गया है। हम मानते हैं कि सुलभ जानकारी और अभिनव उपकरण प्रदान करके, हम कृषि समुदायों को बदलती दुनिया में फलने-फूलने में मदद कर सकते हैं।',
    aboutText2: 'हमारा मिशन पारंपरिक खेती के तरीकों और आधुनिक तकनीक के बीच की खाई को पाटना है। हम वास्तविक समय के मौसम अलर्ट और फसल प्रबंधन सलाह से लेकर वित्तीय सहायता संसाधनों तक, महत्वपूर्ण कृषि जरूरतों के लिए एक ही स्थान पर समाधान प्रदान करते हैं।',
    aboutText3: 'हमारी टीम कृषि के लिए एक स्थायी भविष्य बनाने के लिए समर्पित है, एक समय में एक किसान।',
    contactTitle: 'हमसे संपर्क करें',
    contactText: 'कोई प्रश्न है या समर्थन की आवश्यकता है? नीचे विवरण भरें और हम यथासंभव जल्द से जल्द आपसे संपर्क करेंगे।',
    yourName: 'आपका नाम',
    yourEmail: 'आपका ईमेल',
    yourQuery: 'आपकी क्वेरी',
    submitQuery: 'क्वेरी सबमिट करें',
    reachUs: 'वैकल्पिक रूप से, आप हमसे सीधे संपर्क कर सकते हैं:',
    profileTitle: 'प्रोफ़ाइल',
    profileLoading: 'प्रोफ़ाइल लोड हो रही है...',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    searchCrop: 'एक फसल खोजें...',
    water: 'पानी',
    soil: 'मिट्टी',
    fertilizers: 'उर्वरक',
    pesticidesLabel: 'कीटनाशक',
    weatherTitle: 'मौसम का पूर्वानुमान',
    weatherText2: 'अपने स्थान के लिए अप-टू-डेट मौसम की जानकारी प्राप्त करें और गंभीर मौसम की स्थिति के लिए अलर्ट प्राप्त करें।',
    currentWeather: 'वर्तमान मौसम:',
    alerts: 'अलर्ट:',
    floodAdvisory: 'बाढ़ की चेतावनी जारी',
    rainExpected: 'अगले 24 घंटों में भारी बारिश की उम्मीद है। अनुशंसित कार्रवाई: उचित जल निकासी सुनिश्चित करें और निचले इलाकों की फसलों को सुरक्षित करें।',
    pesticideTitle: 'कीटनाशक और उर्वरक',
    pesticideText2: 'अपनी फसलों और मिट्टी के लिए उपयुक्त कीटनाशकों और उर्वरकों के बारे में जानकारी प्राप्त करें।',
    organicFertilizers: 'जैविक उर्वरक',
    syntheticPesticides: 'सिंथेटिक कीटनाशक',
    investmentTitle: 'निवेश गृह',
    investmentText2: 'अपने वित्तीय भविष्य को सुरक्षित करने में आपकी मदद करने के लिए संसाधन, जिसमें कम ब्याज वाले ऋण और फसल बीमा शामिल हैं।',
    lowInterestLoans: 'कम ब्याज वाले ऋण',
    cropInsurance: 'फसल बीमा',
    theme: 'थीम',
    language: 'भाषा',
    upgradeAccount: 'अपने खाते को अपग्रेड करें',
    upgradeText: 'उन्नत विश्लेषण, व्यक्तिगत सिफारिशें और विशेषज्ञ सहायता जैसी प्रीमियम सुविधाओं को अनलॉक करें।',
    learnMore: 'अधिक जानें और अपग्रेड करें',
  },
  Bengali: {
    home: 'হোম',
    about: 'আমাদের সম্পর্কে',
    contact: 'যোগাযোগ',
    profile: 'প্রোফাইল',
    logout: 'লগ আউট',
    login: 'লগইন',
    signUp: 'সাইন আপ',
    welcome: 'গ্রিনস্পার্কে আপনাকে স্বাগতম',
    tagline: 'কৃষককে ক্ষমতায়ন – ভবিষ্যতের চাষ',
    addressingChallenges: 'মূল চ্যালেঞ্জ মোকাবেলা',
    challengesText: 'জলবায়ু পরিবর্তন, সম্পদ ব্যবস্থাপনা, বাজার অ্যাক্সেস এবং আর্থিক সুরক্ষার মতো অনেক চ্যালেঞ্জের মুখোমুখি হয় কৃষকরা। গ্রিনস্পার্ক এই বাধাগুলি অতিক্রম করতে এবং সমৃদ্ধ হতে প্রয়োজনীয় সরঞ্জাম এবং তথ্য সরবরাহ করে।',
    cropDetails: 'ফসলের বিবরণ',
    cropDetailsText: 'জল, মাটি, এবং সার সম্পর্কে তথ্য পান।',
    weather: 'আবহাওয়া',
    weatherText: 'রিয়েল-টাইম আবহাওয়া আপডেট এবং সতর্কতা।',
    pesticides: 'কীটনাশক',
    pesticideText: 'আপনার ফসলের জন্য উপযুক্ত কীটনাশক এবং সার খুঁজুন।',
    investmentHouse: 'বিনিয়োগ হাউস',
    investmentHouseText: 'ঋণ এবং বীমা বিবরণ অ্যাক্সেস করুন।',
    members: 'সদস্য',
    registeredMembers: 'আমাদের প্ল্যাটফর্মে নিবন্ধিত মোট সদস্য সংখ্যা, যা প্রতিদিন বাড়ছে!',
    help: 'সহায়তা',
    settings: 'সেটিংস',
    chatbot: 'চ্যাটবট',
    aboutTitle: 'গ্রিনস্পার্ক সম্পর্কে',
    aboutText1: 'গ্রিনস্পার্ক একটি বিস্তৃত ডিজিটাল প্ল্যাটফর্ম যা কৃষকদের সমর্থন ও ক্ষমতায়ন করার জন্য ডিজাইন করা হয়েছে। আমরা বিশ্বাস করি যে, সহজলভ্য তথ্য এবং উদ্ভাবনী সরঞ্জাম সরবরাহ করে, আমরা পরিবর্তনশীল বিশ্বে কৃষি সম্প্রদায়কে সমৃদ্ধ হতে সাহায্য করতে পারি।',
    aboutText2: 'আমাদের লক্ষ্য হল ঐতিহ্যবাহী কৃষি পদ্ধতি এবং আধুনিক প্রযুক্তির মধ্যে ব্যবধান পূরণ করা। আমরা রিয়েল-টাইম আবহাওয়া সতর্কতা এবং ফসল ব্যবস্থাপনা পরামর্শ থেকে শুরু করে আর্থিক সহায়তা সংস্থান পর্যন্ত, গুরুত্বপূর্ণ কৃষি প্রয়োজনের জন্য এক-স্টপ সমাধান অফার করি।',
    aboutText3: 'আমাদের দল কৃষির জন্য একটি টেকসই ভবিষ্যৎ গড়তে প্রতিশ্রুতিবদ্ধ।',
    contactTitle: 'আমাদের সাথে যোগাযোগ করুন',
    contactText: 'কোনো প্রশ্ন আছে বা সমর্থনের প্রয়োজন? নিচে বিবরণ পূরণ করুন এবং আমরা যত তাড়াতাড়ি সম্ভব আপনার সাথে যোগাযোগ করব।',
    yourName: 'আপনার নাম',
    yourEmail: 'আপনার ইমেল',
    yourQuery: 'আপনার প্রশ্ন',
    submitQuery: 'প্রশ্ন জমা দিন',
    reachUs: 'বিকল্পভাবে, আপনি সরাসরি আমাদের সাথে যোগাযোগ করতে পারেন:',
    profileTitle: 'প্রোফাইল',
    profileLoading: 'প্রোফাইল লোড হচ্ছে...',
    editProfile: 'প্রোফাইল সম্পাদনা করুন',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    searchCrop: 'একটি ফসল অনুসন্ধান করুন...',
    water: 'জল',
    soil: 'মাটি',
    fertilizers: 'সার',
    pesticidesLabel: 'কীটনাশক',
    weatherTitle: 'আবহাওয়ার পূর্বাভাস',
    weatherText2: 'আপনার অবস্থানের জন্য আপ-টু-ডেট আবহাওয়ার তথ্য পান এবং চরম আবহাওয়ার অবস্থা থেকে আপনার ফসল রক্ষা করার জন্য সতর্কতা এবং কৌশল পান।',
    currentWeather: 'বর্তমান আবহাওয়া:',
    alerts: 'সতর্কতা:',
    floodAdvisory: 'বন্যা সতর্কতা জারি',
    rainExpected: 'পরবর্তী 24 ঘন্টায় ভারী বৃষ্টিপাত আশা করা হচ্ছে। প্রস্তাবিত পদক্ষেপ: সঠিক নিষ্কাশন নিশ্চিত করুন এবং নিম্নভূমির ফসল সুরক্ষিত করুন।',
    pesticideTitle: 'কীটনাশক ও সার',
    pesticideText2: 'আপনার ফসল এবং মাটির জন্য সঠিক কীটনাশক এবং সার সম্পর্কে তথ্য খুঁজুন।',
    organicFertilizers: 'জৈব সার',
    syntheticPesticides: 'সিন্থেটিক কীটনাশক',
    investmentTitle: 'বিনিয়োগ হাউস',
    investmentText2: 'আপনার আর্থিক ভবিষ্যৎ সুরক্ষিত করতে সাহায্য করার জন্য সম্পদ, যার মধ্যে কম সুদে ঋণ এবং শস্য বীমা অন্তর্ভুক্ত রয়েছে।',
    lowInterestLoans: 'কম সুদে ঋণ',
    cropInsurance: 'ফসল বীমা',
    theme: 'থিম',
    language: 'ভাষা',
    upgradeAccount: 'আপনার অ্যাকাউন্ট আপগ্রেড করুন',
    upgradeText: 'উন্নত বিশ্লেষণ, ব্যক্তিগত সুপারিশ এবং বিশেষজ্ঞ সমর্থনের মতো প্রিমিয়াম বৈশিষ্ট্যগুলি আনলক করুন।',
    learnMore: 'আরও জানুন এবং আপগ্রেড করুন',
  },
  Telugu: {
    home: 'హోమ్',
    about: 'మా గురించి',
    contact: 'సంప్రదించండి',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్',
    signUp: 'సైన్ అప్',
    welcome: 'గ్రీన్‌స్పార్క్ కు స్వాగతం',
    tagline: 'రైతుకు సాధికారత – భవిష్యత్తును పండించడం',
    addressingChallenges: 'ప్రధాన సవాళ్లను పరిష్కరించడం',
    challengesText: 'వాతావరణ మార్పు, వనరుల నిర్వహణ, మార్కెట్ యాక్సెస్ మరియు ఆర్థిక భద్రత వంటి అనేక సవాళ్లను నేడు రైతులు ఎదుర్కొంటున్నారు. ఈ అడ్డంకులను అధిగమించి, అభివృద్ధి చెందడానికి గ్రీన్‌స్పార్క్ అవసరమైన ఉపకరణాలు మరియు సమాచారాన్ని అందిస్తుంది.',
    cropDetails: 'పంట వివరాలు',
    cropDetailsText: 'నీరు, నేల మరియు ఎరువుల గురించి సమాచారాన్ని పొందండి.',
    weather: 'వాతావరణం',
    weatherText: 'రియల్-టైమ్ వాతావరణ అప్‌డేట్‌లు మరియు హెచ్చరికలు.',
    pesticides: 'పురుగుమందులు',
    pesticideText: 'మీ పంటలకు సరిపోయే పురుగుమందులు మరియు ఎరువుల గురించి తెలుసుకోండి.',
    investmentHouse: 'పెట్టుబడి గృహం',
    investmentHouseText: 'రుణం మరియు బీమా వివరాలను పొందండి।',
    members: 'సభ్యులు',
    registeredMembers: 'మా ప్లాట్‌ఫారమ్‌లో నమోదైన మొత్తం సభ్యుల సంఖ్య, ఇది ప్రతిరోజూ పెరుగుతోంది!',
    help: 'సహాయం',
    settings: 'సెట్టింగ్స్',
    chatbot: 'చాట్‌బాట్',
    aboutTitle: 'గ్రీన్‌స్పార్క్ గురించి',
    aboutText1: 'గ్రీన్‌స్పార్క్ అనేది రైతులను సపోర్ట్ చేయడానికి మరియు సాధికారత కల్పించడానికి రూపొందించబడిన ఒక సమగ్ర డిజిటల్ ప్లాట్‌ఫారమ్. సులభంగా అందుబాటులో ఉండే సమాచారం మరియు వినూత్న ఉపకరణాలను అందించడం ద్వారా, మేము వ్యవసాయ సమాజాలు మారుతున్న ప్రపంచంలో అభివృద్ధి చెందడానికి సహాయపడతామని మేము నమ్ముతున్నాము।',
    aboutText2: 'సంప్రదాయ వ్యవసాయ పద్ధతులు మరియు ఆధునిక సాంకేతికత మధ్య అంతరాన్ని పూడ్చడమే మా లక్ష్యం. మేము రియల్-టైమ్ వాతావరణ హెచ్చరికలు మరియు పంట నిర్వహణ సలహా నుండి ఆర్థిక సహాయ వనరుల వరకు, ముఖ్యమైన వ్యవసాయ అవసరాలకు ఒకే చోట పరిష్కారం అందిస్తాము।',
    aboutText3: 'మా బృందం వ్యవసాయానికి ఒక స్థిరమైన భవిష్యత్తును నిర్మించడానికి అంకితమై ఉంది, ఒకేసారి ఒక రైతుకు।',
    contactTitle: 'మమ్మల్ని సంప్రదించండి',
    contactText: 'ప్రశ్న ఉందా లేదా మద్దతు కావాలా? క్రింద వివరాలను పూరించండి మరియు మేము వీలైనంత త్వరగా మీకు తిరిగి వస్తాము.',
    yourName: 'మీ పేరు',
    yourEmail: 'మీ ఇమెయిల్',
    yourQuery: 'మీ ప్రశ్న',
    submitQuery: 'ప్రశ్నను సమర్పించండి',
    reachUs: 'ప్రత్యామ్నాయంగా, మీరు మమ్మల్ని నేరుగా సంప్రదించవచ్చు:',
    profileTitle: 'ప్రొఫైల్',
    profileLoading: 'ప్రొఫైల్ లోడ్ అవుతోంది...',
    editProfile: 'ప్రొఫైల్ సవరించండి',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    searchCrop: 'పంట కోసం వెతకండి...',
    water: 'నీరు',
    soil: 'నేల',
    fertilizers: 'ఎరువులు',
    pesticidesLabel: 'పురుగుమందులు',
    weatherTitle: 'వాతావరణ సూచన',
    weatherText2: 'మీ స్థానం కోసం అప్‌డేట్ చేసిన వాతావరణ సమాచారాన్ని పొందండి మరియు తీవ్రమైన వాతావరణ పరిస్థితుల కోసం హెచ్చరికలు మరియు పరిష్కారాలను పొందండి.',
    currentWeather: 'ప్రస్తుత వాతావరణం:',
    alerts: 'హెచ్చరికలు:',
    floodAdvisory: 'వరద హెచ్చరిక అమల్లో ఉంది',
    rainExpected: 'రాబోయే 24 గంటల్లో భారీ వర్షపాతం. సిఫార్సు చేసిన చర్య: సరైన పారుదలని నిర్ధారించండి మరియు దిగువ పంటలను సురక్షితం చేయండి.',
    pesticideTitle: 'పురుగుమందులు & ఎరువులు',
    pesticideText2: 'మీ పంటలు మరియు నేలకు సరైన పురుగుమందులు మరియు ఎరువుల గురించి సమాచారాన్ని పొందండి.',
    organicFertilizers: 'సేంద్రీయ ఎరువులు',
    syntheticPesticides: 'సింథటిక్ పురుగుమందులు',
    investmentTitle: 'పెట్టుబడి గృహం',
    investmentText2: 'తక్కువ వడ్డీ రుణాలు మరియు పంట బీమాతో సహా మీ ఆర్థిక భవిష్యత్తును సురక్షితం చేయడానికి మీకు సహాయపడే వనరులు.',
    lowInterestLoans: 'తక్కువ వడ్డీ రుణాలు',
    cropInsurance: 'పంట బీమా',
    theme: 'థీమ్',
    language: 'భాష',
    upgradeAccount: 'మీ ఖాతాను అప్‌గ్రేడ్ చేయండి',
    upgradeText: 'అధునాతన విశ్లేషణలు, వ్యక్తిగతీకరించిన సిఫార్సులు మరియు నిపుణుల మద్దతు వంటి ప్రీమియం ఫీచర్లను అన్‌లాక్ చేయండి।',
    learnMore: 'మరిన్ని తెలుసుకోండి & అప్‌గ్రేడ్ చేయండి',
  },
};
